version: '{branch}-build{build}'
image: Ubuntu1804

skip_commits:
  files:
    - '**/*.md'
    
build_script:
  - sh: dotnet build -c Release

test_script:
  - sh: dotnet test -c Release --no-build

after_test:
  - sh: chmod +x pack.sh && ./pack.sh

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: Nuget
- path: '**\artifacts\myget\*.nupkg'
  name: Myget
  
deploy:
- provider: NuGet
  api_key:
    secure: zRa2gcYSMh0ddc8hB61BbGf7Z3Zx0y106S4XIkOWPPAFg3DmNP4qt+9LEDgKXteO
  artifact: NuGet
  on:
    appveyor_repo_tag: true   
- provider: NuGet
  server: https://www.myget.org/F/phnx47-beta/api/v2/package
  api_key:
    secure: Smuwoi47XyX6b6x66VpPnnL96F3cl1nukALrFnZo1Oony38dzouByG7pnt6DX4HT
  symbol_server: https://www.myget.org/F/phnx47-beta/symbols/api/v2/package
  artifact: MyGet
  on:
    branch: master
    appveyor_repo_tag: false
