version: '{branch}-build{build}'
image: Ubuntu1804

environment:
  codecov_token:
    secure: ChmOZrgQci5dvY1J2U9YomGaXw78lChaCt3ucv0ehu/p4wt90sB+yo3lVZ8ISD72

skip_commits:
  files:
    - '**/*.md'

build_script:
  - sh: dotnet build -c Release

test_script:
  - sh: chmod +x test.sh && ./test.sh

after_test:
  - sh: chmod +x pack.sh && ./pack.sh

artifacts:
  - path: '**/artifacts/nuget/*.nupkg'
    name: NuGet
  - path: '**/artifacts/myget/*.nupkg'
    name: MyGet

deploy:
  - provider: NuGet
    api_key:
      secure: oixT0UsEshJpA1t6OQhZ9EHfe4BqphgTXCWO98UJsQYTBA95GwqcSpRjt8ROl98E
    artifact: NuGet
    on:
      APPVEYOR_REPO_TAG: true
  - provider: NuGet
    server: https://www.myget.org/F/prometheus-client-net/api/v2/package
    api_key:
      secure: DvXZQgy0wcMjR87Zt1qBB9YaDmEiAAiylRxVFfnvkYmfD+oYUetgCi1B036DJZGF
    symbol_server: https://www.myget.org/F/prometheus-client-net/symbols/api/v2/package
    artifact: MyGet
    on:
      branch: master
      APPVEYOR_REPO_TAG: false
