name: "branch"

on:
  push:
    branches:
      - '*'
      - '!master'
    tags:
      - '!refs/tags/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
      - name: Restore
        run: dotnet restore
      - name: Tests
        run: dotnet test --no-restore /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
      - name: Publish to Codecov
        uses: codecov/codecov-action@v1
